repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: external-dns6
    namespace: kube-addons6
    chart: bitnami/external-dns
    version: 6.12.1
    values:
      - provider: azure
        azure:
          resourceGroup: {{ requiredEnv "RG_NAME" }}
          tenantId: {{ requiredEnv "TENANT_ID" }}
          subscriptionId: {{ requiredEnv "AZURE_SUB_ID" }}
          useManagedIdentityExtension: true
        logLevel: {{ env "EXTERNALDNS_LOG_LEVEL" | default "debug" }}
        domainFilters:
          - test.raykao.dev
        txtOwnerId: external-dns